### PR TITLE
Add error messages to Braintree exceptions

### PR DESCRIPTION
**Pull request by ykrasik**
By default, most Braintree exceptions come without error messages. The error is determined by the exception type. The code that handles this in the Braintree SDK is located it com.braintreegateway.util.Http::257-275
The result is an error that is reported back without a message, something we've encountered in production.
I've added error messages for 2 cases:
* Credential validation fails (That exception is always created without a message)
* AuthorizationException which seems to be an exception that could contain a message (according to the Braintree code), but doesn't always.
I added only these 2 cases, because it's what we encountered in prod.

### CODE REVIEW

**Comment by ykrasik** [comment]
OK, so I went ahead and added messages to the exceptions that I saw being throw without a clear message.

**Comment by ohadraz** [comment]
Super cool dude, but where are the tests?... :-/

Plus, I believe that the suggested solution may provide extra information the user has nothing to do with, has the potential of actually hide details which might be usable for debugging, and perhaps even to provide misleading information.
What am I talking about?
Well, the "original" code, took both error message and cause of Braintree's SDK exception, and populated it in the `PaymentErrorException`. Those details might be valuable.
In the suggested fix, some exceptions are being populated with hard coded messages. I understand some of Braintree's SDK exceptions holds no messages. But we can get a good clue of what had happened based on the exception's cause, which is also delegated to the `PaymentErrorException`.
So where does the message adds no information for the user?
For example, the `NotFoundException`. There are no details as to what resource was not found, and what should the user do in order to fix it.
Where might details get hidden? 
For example, if, say, `ServerException`, will begin having message (due to some change made in Braintree's servers). With the suggested solution, this (perhaps valuable information) will be overwritten by the hard coded message.
And where information might be misleading?
For example, with the `AuthenticationException`. Let's say communication was not done using "legacy" merchant key credentials, but rather OAuth (we talked about this option a couple of days ago). The suggested hard coded message may cause the user debugging the problem to believe the issue is with wrong "legacy" credentials, while the problem actually has to do with OAuth.

How do I believe we should tackle these issues?
I think we should take the best effort approach (by this I mean: `Option(e.getMessage).getOrElse("...")` approach) for exceptions that currently have no message. This way, details won't get hidden with hard coded message.
In cases that are depending on configuration or other "external" aspects, consider having a message which is not too specific (and that if a message is needed at all; as I said, we can get a clue by the cause).

**Comment by ykrasik** [comment]
I'll revise the code according to your suggestions. Actually from looking at it, we can just refer to the cause of PaymentErrorException on our end to understand what's going on, so as you said - this PR may not be needed at all. Is PaymentErrorException a wrapper for provider-domain errors?

**Comment by ohadraz** [comment]
paylib-braintree is a concrete implementation of paylib for Braintree; there are, like, 17 of those.
We need to have specific provider exceptions be generalized for the common interface. This is why it is there. Plus, it immediately suggest the problem (i.e., there's the error exception, which represent that something went wrong, maybe with the data in the request, maybe at the server side, and there's the reject exception that represent that everything went fine, but the payment was rejected for whatever reason).
And yeah, I agree with you that this PR is not really needed...

**Pull request closed without merging**
